export const SAVE_USER_LIST = 'SAVE_USER_LIST';
export const FILTER_USER_LIST = 'FILTER_USER_LIST';
export const SET_CURRENT_RECORD = 'SET_CURRENT_RECORD';
export const SAVE_USER_POSTS = 'SAVE_USER_POSTS';